// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: proto-merge.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Merger_Download_FullMethodName  = "/merge.Merger/Download"
	Merger_Describe_FullMethodName  = "/merge.Merger/Describe"
	Merger_Transform_FullMethodName = "/merge.Merger/Transform"
	Merger_Build_FullMethodName     = "/merge.Merger/Build"
)

// MergerClient is the client API for Merger service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Merger service composes all operations.
type MergerClient interface {
	// Download fetches .proto files from source repos.
	Download(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StringValue, descriptorpb.FileDescriptorProto], error)
	// Describe converts descriptors to human-readable StringValue output.
	Describe(ctx context.Context, in *Descriptor, opts ...grpc.CallOption) (*StringValue, error)
	// Transform applies modifications to a file descriptor.
	Transform(ctx context.Context, in *WalkRequest, opts ...grpc.CallOption) (*WalkResponse, error)
	// Build orchestrates: download sources, parse, transform, bundle.
	Build(ctx context.Context, in *BuildRequest, opts ...grpc.CallOption) (*BuildResponse, error)
}

type mergerClient struct {
	cc grpc.ClientConnInterface
}

func NewMergerClient(cc grpc.ClientConnInterface) MergerClient {
	return &mergerClient{cc}
}

func (c *mergerClient) Download(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StringValue, descriptorpb.FileDescriptorProto], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Merger_ServiceDesc.Streams[0], Merger_Download_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StringValue, descriptorpb.FileDescriptorProto]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Merger_DownloadClient = grpc.BidiStreamingClient[StringValue, descriptorpb.FileDescriptorProto]

func (c *mergerClient) Describe(ctx context.Context, in *Descriptor, opts ...grpc.CallOption) (*StringValue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StringValue)
	err := c.cc.Invoke(ctx, Merger_Describe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mergerClient) Transform(ctx context.Context, in *WalkRequest, opts ...grpc.CallOption) (*WalkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WalkResponse)
	err := c.cc.Invoke(ctx, Merger_Transform_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mergerClient) Build(ctx context.Context, in *BuildRequest, opts ...grpc.CallOption) (*BuildResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BuildResponse)
	err := c.cc.Invoke(ctx, Merger_Build_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MergerServer is the server API for Merger service.
// All implementations must embed UnimplementedMergerServer
// for forward compatibility.
//
// Merger service composes all operations.
type MergerServer interface {
	// Download fetches .proto files from source repos.
	Download(grpc.BidiStreamingServer[StringValue, descriptorpb.FileDescriptorProto]) error
	// Describe converts descriptors to human-readable StringValue output.
	Describe(context.Context, *Descriptor) (*StringValue, error)
	// Transform applies modifications to a file descriptor.
	Transform(context.Context, *WalkRequest) (*WalkResponse, error)
	// Build orchestrates: download sources, parse, transform, bundle.
	Build(context.Context, *BuildRequest) (*BuildResponse, error)
	mustEmbedUnimplementedMergerServer()
}

// UnimplementedMergerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMergerServer struct{}

func (UnimplementedMergerServer) Download(grpc.BidiStreamingServer[StringValue, descriptorpb.FileDescriptorProto]) error {
	return status.Errorf(codes.Unimplemented, "method Download not implemented")
}
func (UnimplementedMergerServer) Describe(context.Context, *Descriptor) (*StringValue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Describe not implemented")
}
func (UnimplementedMergerServer) Transform(context.Context, *WalkRequest) (*WalkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Transform not implemented")
}
func (UnimplementedMergerServer) Build(context.Context, *BuildRequest) (*BuildResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Build not implemented")
}
func (UnimplementedMergerServer) mustEmbedUnimplementedMergerServer() {}
func (UnimplementedMergerServer) testEmbeddedByValue()                {}

// UnsafeMergerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MergerServer will
// result in compilation errors.
type UnsafeMergerServer interface {
	mustEmbedUnimplementedMergerServer()
}

func RegisterMergerServer(s grpc.ServiceRegistrar, srv MergerServer) {
	// If the following call pancis, it indicates UnimplementedMergerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Merger_ServiceDesc, srv)
}

func _Merger_Download_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MergerServer).Download(&grpc.GenericServerStream[StringValue, descriptorpb.FileDescriptorProto]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Merger_DownloadServer = grpc.BidiStreamingServer[StringValue, descriptorpb.FileDescriptorProto]

func _Merger_Describe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Descriptor)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MergerServer).Describe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Merger_Describe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MergerServer).Describe(ctx, req.(*Descriptor))
	}
	return interceptor(ctx, in, info, handler)
}

func _Merger_Transform_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WalkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MergerServer).Transform(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Merger_Transform_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MergerServer).Transform(ctx, req.(*WalkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Merger_Build_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MergerServer).Build(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Merger_Build_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MergerServer).Build(ctx, req.(*BuildRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Merger_ServiceDesc is the grpc.ServiceDesc for Merger service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Merger_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "merge.Merger",
	HandlerType: (*MergerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Describe",
			Handler:    _Merger_Describe_Handler,
		},
		{
			MethodName: "Transform",
			Handler:    _Merger_Transform_Handler,
		},
		{
			MethodName: "Build",
			Handler:    _Merger_Build_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Download",
			Handler:       _Merger_Download_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto-merge.proto",
}
