// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto-merge.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StringValue is a simple wrapper for string output from RPCs.
type StringValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringValue) Reset() {
	*x = StringValue{}
	mi := &file_proto_merge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringValue) ProtoMessage() {}

func (x *StringValue) ProtoReflect() protoreflect.Message {
	mi := &file_proto_merge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringValue.ProtoReflect.Descriptor instead.
func (*StringValue) Descriptor() ([]byte, []int) {
	return file_proto_merge_proto_rawDescGZIP(), []int{0}
}

func (x *StringValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// Descriptor is a union of all proto descriptor types.
type Descriptor struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Descriptor_Message
	//	*Descriptor_Method
	//	*Descriptor_Service
	//	*Descriptor_File
	//	*Descriptor_Field
	//	*Descriptor_Enum
	Kind          isDescriptor_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Descriptor) Reset() {
	*x = Descriptor{}
	mi := &file_proto_merge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Descriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Descriptor) ProtoMessage() {}

func (x *Descriptor) ProtoReflect() protoreflect.Message {
	mi := &file_proto_merge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Descriptor.ProtoReflect.Descriptor instead.
func (*Descriptor) Descriptor() ([]byte, []int) {
	return file_proto_merge_proto_rawDescGZIP(), []int{1}
}

func (x *Descriptor) GetKind() isDescriptor_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Descriptor) GetMessage() *descriptorpb.DescriptorProto {
	if x != nil {
		if x, ok := x.Kind.(*Descriptor_Message); ok {
			return x.Message
		}
	}
	return nil
}

func (x *Descriptor) GetMethod() *descriptorpb.MethodDescriptorProto {
	if x != nil {
		if x, ok := x.Kind.(*Descriptor_Method); ok {
			return x.Method
		}
	}
	return nil
}

func (x *Descriptor) GetService() *descriptorpb.ServiceDescriptorProto {
	if x != nil {
		if x, ok := x.Kind.(*Descriptor_Service); ok {
			return x.Service
		}
	}
	return nil
}

func (x *Descriptor) GetFile() *descriptorpb.FileDescriptorProto {
	if x != nil {
		if x, ok := x.Kind.(*Descriptor_File); ok {
			return x.File
		}
	}
	return nil
}

func (x *Descriptor) GetField() *descriptorpb.FieldDescriptorProto {
	if x != nil {
		if x, ok := x.Kind.(*Descriptor_Field); ok {
			return x.Field
		}
	}
	return nil
}

func (x *Descriptor) GetEnum() *descriptorpb.EnumDescriptorProto {
	if x != nil {
		if x, ok := x.Kind.(*Descriptor_Enum); ok {
			return x.Enum
		}
	}
	return nil
}

type isDescriptor_Kind interface {
	isDescriptor_Kind()
}

type Descriptor_Message struct {
	Message *descriptorpb.DescriptorProto `protobuf:"bytes,1,opt,name=message,proto3,oneof"`
}

type Descriptor_Method struct {
	Method *descriptorpb.MethodDescriptorProto `protobuf:"bytes,2,opt,name=method,proto3,oneof"`
}

type Descriptor_Service struct {
	Service *descriptorpb.ServiceDescriptorProto `protobuf:"bytes,3,opt,name=service,proto3,oneof"`
}

type Descriptor_File struct {
	File *descriptorpb.FileDescriptorProto `protobuf:"bytes,4,opt,name=file,proto3,oneof"`
}

type Descriptor_Field struct {
	Field *descriptorpb.FieldDescriptorProto `protobuf:"bytes,5,opt,name=field,proto3,oneof"`
}

type Descriptor_Enum struct {
	Enum *descriptorpb.EnumDescriptorProto `protobuf:"bytes,6,opt,name=enum,proto3,oneof"`
}

func (*Descriptor_Message) isDescriptor_Kind() {}

func (*Descriptor_Method) isDescriptor_Kind() {}

func (*Descriptor_Service) isDescriptor_Kind() {}

func (*Descriptor_File) isDescriptor_Kind() {}

func (*Descriptor_Field) isDescriptor_Kind() {}

func (*Descriptor_Enum) isDescriptor_Kind() {}

// FieldModification describes adding or changing a field on messages.
type FieldModification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FieldName     string                 `protobuf:"bytes,1,opt,name=field_name,json=fieldName,proto3" json:"field_name,omitempty"`
	FieldType     int32                  `protobuf:"varint,2,opt,name=field_type,json=fieldType,proto3" json:"field_type,omitempty"`       // google.protobuf.FieldDescriptorProto.Type value
	TypeName      string                 `protobuf:"bytes,3,opt,name=type_name,json=typeName,proto3" json:"type_name,omitempty"`           // for message/enum references
	FieldNumber   int32                  `protobuf:"varint,4,opt,name=field_number,json=fieldNumber,proto3" json:"field_number,omitempty"` // 0 = auto-assign
	Repeated      bool                   `protobuf:"varint,5,opt,name=repeated,proto3" json:"repeated,omitempty"`
	TargetMessage string                 `protobuf:"bytes,6,opt,name=target_message,json=targetMessage,proto3" json:"target_message,omitempty"` // empty = apply to all messages
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldModification) Reset() {
	*x = FieldModification{}
	mi := &file_proto_merge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldModification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldModification) ProtoMessage() {}

func (x *FieldModification) ProtoReflect() protoreflect.Message {
	mi := &file_proto_merge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldModification.ProtoReflect.Descriptor instead.
func (*FieldModification) Descriptor() ([]byte, []int) {
	return file_proto_merge_proto_rawDescGZIP(), []int{2}
}

func (x *FieldModification) GetFieldName() string {
	if x != nil {
		return x.FieldName
	}
	return ""
}

func (x *FieldModification) GetFieldType() int32 {
	if x != nil {
		return x.FieldType
	}
	return 0
}

func (x *FieldModification) GetTypeName() string {
	if x != nil {
		return x.TypeName
	}
	return ""
}

func (x *FieldModification) GetFieldNumber() int32 {
	if x != nil {
		return x.FieldNumber
	}
	return 0
}

func (x *FieldModification) GetRepeated() bool {
	if x != nil {
		return x.Repeated
	}
	return false
}

func (x *FieldModification) GetTargetMessage() string {
	if x != nil {
		return x.TargetMessage
	}
	return ""
}

// ServiceModification describes adding methods to services.
type ServiceModification struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MethodName      string                 `protobuf:"bytes,1,opt,name=method_name,json=methodName,proto3" json:"method_name,omitempty"`
	InputType       string                 `protobuf:"bytes,2,opt,name=input_type,json=inputType,proto3" json:"input_type,omitempty"`
	OutputType      string                 `protobuf:"bytes,3,opt,name=output_type,json=outputType,proto3" json:"output_type,omitempty"`
	ClientStreaming bool                   `protobuf:"varint,4,opt,name=client_streaming,json=clientStreaming,proto3" json:"client_streaming,omitempty"`
	ServerStreaming bool                   `protobuf:"varint,5,opt,name=server_streaming,json=serverStreaming,proto3" json:"server_streaming,omitempty"`
	TargetService   string                 `protobuf:"bytes,6,opt,name=target_service,json=targetService,proto3" json:"target_service,omitempty"` // empty = apply to all services
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ServiceModification) Reset() {
	*x = ServiceModification{}
	mi := &file_proto_merge_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceModification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceModification) ProtoMessage() {}

func (x *ServiceModification) ProtoReflect() protoreflect.Message {
	mi := &file_proto_merge_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceModification.ProtoReflect.Descriptor instead.
func (*ServiceModification) Descriptor() ([]byte, []int) {
	return file_proto_merge_proto_rawDescGZIP(), []int{3}
}

func (x *ServiceModification) GetMethodName() string {
	if x != nil {
		return x.MethodName
	}
	return ""
}

func (x *ServiceModification) GetInputType() string {
	if x != nil {
		return x.InputType
	}
	return ""
}

func (x *ServiceModification) GetOutputType() string {
	if x != nil {
		return x.OutputType
	}
	return ""
}

func (x *ServiceModification) GetClientStreaming() bool {
	if x != nil {
		return x.ClientStreaming
	}
	return false
}

func (x *ServiceModification) GetServerStreaming() bool {
	if x != nil {
		return x.ServerStreaming
	}
	return false
}

func (x *ServiceModification) GetTargetService() string {
	if x != nil {
		return x.TargetService
	}
	return ""
}

// TransformCommand describes a transformation to apply.
type TransformCommand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Command:
	//
	//	*TransformCommand_AddField
	//	*TransformCommand_AddMethod
	//	*TransformCommand_MergeMessages
	//	*TransformCommand_Rename
	//	*TransformCommand_RemoveField
	Command       isTransformCommand_Command `protobuf_oneof:"command"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransformCommand) Reset() {
	*x = TransformCommand{}
	mi := &file_proto_merge_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransformCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransformCommand) ProtoMessage() {}

func (x *TransformCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_merge_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransformCommand.ProtoReflect.Descriptor instead.
func (*TransformCommand) Descriptor() ([]byte, []int) {
	return file_proto_merge_proto_rawDescGZIP(), []int{4}
}

func (x *TransformCommand) GetCommand() isTransformCommand_Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *TransformCommand) GetAddField() *FieldModification {
	if x != nil {
		if x, ok := x.Command.(*TransformCommand_AddField); ok {
			return x.AddField
		}
	}
	return nil
}

func (x *TransformCommand) GetAddMethod() *ServiceModification {
	if x != nil {
		if x, ok := x.Command.(*TransformCommand_AddMethod); ok {
			return x.AddMethod
		}
	}
	return nil
}

func (x *TransformCommand) GetMergeMessages() *MergeMessages {
	if x != nil {
		if x, ok := x.Command.(*TransformCommand_MergeMessages); ok {
			return x.MergeMessages
		}
	}
	return nil
}

func (x *TransformCommand) GetRename() *RenameSymbol {
	if x != nil {
		if x, ok := x.Command.(*TransformCommand_Rename); ok {
			return x.Rename
		}
	}
	return nil
}

func (x *TransformCommand) GetRemoveField() *RemoveField {
	if x != nil {
		if x, ok := x.Command.(*TransformCommand_RemoveField); ok {
			return x.RemoveField
		}
	}
	return nil
}

type isTransformCommand_Command interface {
	isTransformCommand_Command()
}

type TransformCommand_AddField struct {
	AddField *FieldModification `protobuf:"bytes,1,opt,name=add_field,json=addField,proto3,oneof"`
}

type TransformCommand_AddMethod struct {
	AddMethod *ServiceModification `protobuf:"bytes,2,opt,name=add_method,json=addMethod,proto3,oneof"`
}

type TransformCommand_MergeMessages struct {
	MergeMessages *MergeMessages `protobuf:"bytes,3,opt,name=merge_messages,json=mergeMessages,proto3,oneof"`
}

type TransformCommand_Rename struct {
	Rename *RenameSymbol `protobuf:"bytes,4,opt,name=rename,proto3,oneof"`
}

type TransformCommand_RemoveField struct {
	RemoveField *RemoveField `protobuf:"bytes,5,opt,name=remove_field,json=removeField,proto3,oneof"`
}

func (*TransformCommand_AddField) isTransformCommand_Command() {}

func (*TransformCommand_AddMethod) isTransformCommand_Command() {}

func (*TransformCommand_MergeMessages) isTransformCommand_Command() {}

func (*TransformCommand_Rename) isTransformCommand_Command() {}

func (*TransformCommand_RemoveField) isTransformCommand_Command() {}

// MergeMessages combines two message types into one.
type MergeMessages struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceMessage string                 `protobuf:"bytes,1,opt,name=source_message,json=sourceMessage,proto3" json:"source_message,omitempty"`
	TargetMessage string                 `protobuf:"bytes,2,opt,name=target_message,json=targetMessage,proto3" json:"target_message,omitempty"`
	ResultName    string                 `protobuf:"bytes,3,opt,name=result_name,json=resultName,proto3" json:"result_name,omitempty"` // empty = use target name
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MergeMessages) Reset() {
	*x = MergeMessages{}
	mi := &file_proto_merge_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MergeMessages) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergeMessages) ProtoMessage() {}

func (x *MergeMessages) ProtoReflect() protoreflect.Message {
	mi := &file_proto_merge_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MergeMessages.ProtoReflect.Descriptor instead.
func (*MergeMessages) Descriptor() ([]byte, []int) {
	return file_proto_merge_proto_rawDescGZIP(), []int{5}
}

func (x *MergeMessages) GetSourceMessage() string {
	if x != nil {
		return x.SourceMessage
	}
	return ""
}

func (x *MergeMessages) GetTargetMessage() string {
	if x != nil {
		return x.TargetMessage
	}
	return ""
}

func (x *MergeMessages) GetResultName() string {
	if x != nil {
		return x.ResultName
	}
	return ""
}

// RenameSymbol renames a message, service, field, or method.
type RenameSymbol struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OldName       string                 `protobuf:"bytes,1,opt,name=old_name,json=oldName,proto3" json:"old_name,omitempty"`
	NewName       string                 `protobuf:"bytes,2,opt,name=new_name,json=newName,proto3" json:"new_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameSymbol) Reset() {
	*x = RenameSymbol{}
	mi := &file_proto_merge_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameSymbol) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameSymbol) ProtoMessage() {}

func (x *RenameSymbol) ProtoReflect() protoreflect.Message {
	mi := &file_proto_merge_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameSymbol.ProtoReflect.Descriptor instead.
func (*RenameSymbol) Descriptor() ([]byte, []int) {
	return file_proto_merge_proto_rawDescGZIP(), []int{6}
}

func (x *RenameSymbol) GetOldName() string {
	if x != nil {
		return x.OldName
	}
	return ""
}

func (x *RenameSymbol) GetNewName() string {
	if x != nil {
		return x.NewName
	}
	return ""
}

// RemoveField removes a field from a message.
type RemoveField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageName   string                 `protobuf:"bytes,1,opt,name=message_name,json=messageName,proto3" json:"message_name,omitempty"`
	FieldName     string                 `protobuf:"bytes,2,opt,name=field_name,json=fieldName,proto3" json:"field_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveField) Reset() {
	*x = RemoveField{}
	mi := &file_proto_merge_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveField) ProtoMessage() {}

func (x *RemoveField) ProtoReflect() protoreflect.Message {
	mi := &file_proto_merge_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveField.ProtoReflect.Descriptor instead.
func (*RemoveField) Descriptor() ([]byte, []int) {
	return file_proto_merge_proto_rawDescGZIP(), []int{7}
}

func (x *RemoveField) GetMessageName() string {
	if x != nil {
		return x.MessageName
	}
	return ""
}

func (x *RemoveField) GetFieldName() string {
	if x != nil {
		return x.FieldName
	}
	return ""
}

// WalkRequest walks a file descriptor applying method-level transforms.
type WalkRequest struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	File          *descriptorpb.FileDescriptorProto `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	Commands      []*TransformCommand               `protobuf:"bytes,2,rep,name=commands,proto3" json:"commands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WalkRequest) Reset() {
	*x = WalkRequest{}
	mi := &file_proto_merge_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalkRequest) ProtoMessage() {}

func (x *WalkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_merge_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalkRequest.ProtoReflect.Descriptor instead.
func (*WalkRequest) Descriptor() ([]byte, []int) {
	return file_proto_merge_proto_rawDescGZIP(), []int{8}
}

func (x *WalkRequest) GetFile() *descriptorpb.FileDescriptorProto {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *WalkRequest) GetCommands() []*TransformCommand {
	if x != nil {
		return x.Commands
	}
	return nil
}

// WalkResponse is the transformed file descriptor.
type WalkResponse struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	File          *descriptorpb.FileDescriptorProto `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	Log           []string                          `protobuf:"bytes,2,rep,name=log,proto3" json:"log,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WalkResponse) Reset() {
	*x = WalkResponse{}
	mi := &file_proto_merge_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalkResponse) ProtoMessage() {}

func (x *WalkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_merge_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalkResponse.ProtoReflect.Descriptor instead.
func (*WalkResponse) Descriptor() ([]byte, []int) {
	return file_proto_merge_proto_rawDescGZIP(), []int{9}
}

func (x *WalkResponse) GetFile() *descriptorpb.FileDescriptorProto {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *WalkResponse) GetLog() []string {
	if x != nil {
		return x.Log
	}
	return nil
}

// BuildRequest orchestrates download + transform pipeline.
type BuildRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceRepos   []string               `protobuf:"bytes,1,rep,name=source_repos,json=sourceRepos,proto3" json:"source_repos,omitempty"` // GitHub org/user names to scan
	Commands      []*TransformCommand    `protobuf:"bytes,2,rep,name=commands,proto3" json:"commands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildRequest) Reset() {
	*x = BuildRequest{}
	mi := &file_proto_merge_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildRequest) ProtoMessage() {}

func (x *BuildRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_merge_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildRequest.ProtoReflect.Descriptor instead.
func (*BuildRequest) Descriptor() ([]byte, []int) {
	return file_proto_merge_proto_rawDescGZIP(), []int{10}
}

func (x *BuildRequest) GetSourceRepos() []string {
	if x != nil {
		return x.SourceRepos
	}
	return nil
}

func (x *BuildRequest) GetCommands() []*TransformCommand {
	if x != nil {
		return x.Commands
	}
	return nil
}

// BuildResponse contains the processed results.
type BuildResponse struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	Files         []*descriptorpb.FileDescriptorProto `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	Bundled       *descriptorpb.FileDescriptorProto   `protobuf:"bytes,2,opt,name=bundled,proto3" json:"bundled,omitempty"`
	Log           []string                            `protobuf:"bytes,3,rep,name=log,proto3" json:"log,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildResponse) Reset() {
	*x = BuildResponse{}
	mi := &file_proto_merge_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildResponse) ProtoMessage() {}

func (x *BuildResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_merge_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildResponse.ProtoReflect.Descriptor instead.
func (*BuildResponse) Descriptor() ([]byte, []int) {
	return file_proto_merge_proto_rawDescGZIP(), []int{11}
}

func (x *BuildResponse) GetFiles() []*descriptorpb.FileDescriptorProto {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *BuildResponse) GetBundled() *descriptorpb.FileDescriptorProto {
	if x != nil {
		return x.Bundled
	}
	return nil
}

func (x *BuildResponse) GetLog() []string {
	if x != nil {
		return x.Log
	}
	return nil
}

var File_proto_merge_proto protoreflect.FileDescriptor

const file_proto_merge_proto_rawDesc = "" +
	"\n" +
	"\x11proto-merge.proto\x12\x05merge\x1a google/protobuf/descriptor.proto\"#\n" +
	"\vStringValue\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"\x90\x03\n" +
	"\n" +
	"Descriptor\x12<\n" +
	"\amessage\x18\x01 \x01(\v2 .google.protobuf.DescriptorProtoH\x00R\amessage\x12@\n" +
	"\x06method\x18\x02 \x01(\v2&.google.protobuf.MethodDescriptorProtoH\x00R\x06method\x12C\n" +
	"\aservice\x18\x03 \x01(\v2'.google.protobuf.ServiceDescriptorProtoH\x00R\aservice\x12:\n" +
	"\x04file\x18\x04 \x01(\v2$.google.protobuf.FileDescriptorProtoH\x00R\x04file\x12=\n" +
	"\x05field\x18\x05 \x01(\v2%.google.protobuf.FieldDescriptorProtoH\x00R\x05field\x12:\n" +
	"\x04enum\x18\x06 \x01(\v2$.google.protobuf.EnumDescriptorProtoH\x00R\x04enumB\x06\n" +
	"\x04kind\"\xd4\x01\n" +
	"\x11FieldModification\x12\x1d\n" +
	"\n" +
	"field_name\x18\x01 \x01(\tR\tfieldName\x12\x1d\n" +
	"\n" +
	"field_type\x18\x02 \x01(\x05R\tfieldType\x12\x1b\n" +
	"\ttype_name\x18\x03 \x01(\tR\btypeName\x12!\n" +
	"\ffield_number\x18\x04 \x01(\x05R\vfieldNumber\x12\x1a\n" +
	"\brepeated\x18\x05 \x01(\bR\brepeated\x12%\n" +
	"\x0etarget_message\x18\x06 \x01(\tR\rtargetMessage\"\xf3\x01\n" +
	"\x13ServiceModification\x12\x1f\n" +
	"\vmethod_name\x18\x01 \x01(\tR\n" +
	"methodName\x12\x1d\n" +
	"\n" +
	"input_type\x18\x02 \x01(\tR\tinputType\x12\x1f\n" +
	"\voutput_type\x18\x03 \x01(\tR\n" +
	"outputType\x12)\n" +
	"\x10client_streaming\x18\x04 \x01(\bR\x0fclientStreaming\x12)\n" +
	"\x10server_streaming\x18\x05 \x01(\bR\x0fserverStreaming\x12%\n" +
	"\x0etarget_service\x18\x06 \x01(\tR\rtargetService\"\xba\x02\n" +
	"\x10TransformCommand\x127\n" +
	"\tadd_field\x18\x01 \x01(\v2\x18.merge.FieldModificationH\x00R\baddField\x12;\n" +
	"\n" +
	"add_method\x18\x02 \x01(\v2\x1a.merge.ServiceModificationH\x00R\taddMethod\x12=\n" +
	"\x0emerge_messages\x18\x03 \x01(\v2\x14.merge.MergeMessagesH\x00R\rmergeMessages\x12-\n" +
	"\x06rename\x18\x04 \x01(\v2\x13.merge.RenameSymbolH\x00R\x06rename\x127\n" +
	"\fremove_field\x18\x05 \x01(\v2\x12.merge.RemoveFieldH\x00R\vremoveFieldB\t\n" +
	"\acommand\"~\n" +
	"\rMergeMessages\x12%\n" +
	"\x0esource_message\x18\x01 \x01(\tR\rsourceMessage\x12%\n" +
	"\x0etarget_message\x18\x02 \x01(\tR\rtargetMessage\x12\x1f\n" +
	"\vresult_name\x18\x03 \x01(\tR\n" +
	"resultName\"D\n" +
	"\fRenameSymbol\x12\x19\n" +
	"\bold_name\x18\x01 \x01(\tR\aoldName\x12\x19\n" +
	"\bnew_name\x18\x02 \x01(\tR\anewName\"O\n" +
	"\vRemoveField\x12!\n" +
	"\fmessage_name\x18\x01 \x01(\tR\vmessageName\x12\x1d\n" +
	"\n" +
	"field_name\x18\x02 \x01(\tR\tfieldName\"|\n" +
	"\vWalkRequest\x128\n" +
	"\x04file\x18\x01 \x01(\v2$.google.protobuf.FileDescriptorProtoR\x04file\x123\n" +
	"\bcommands\x18\x02 \x03(\v2\x17.merge.TransformCommandR\bcommands\"Z\n" +
	"\fWalkResponse\x128\n" +
	"\x04file\x18\x01 \x01(\v2$.google.protobuf.FileDescriptorProtoR\x04file\x12\x10\n" +
	"\x03log\x18\x02 \x03(\tR\x03log\"f\n" +
	"\fBuildRequest\x12!\n" +
	"\fsource_repos\x18\x01 \x03(\tR\vsourceRepos\x123\n" +
	"\bcommands\x18\x02 \x03(\v2\x17.merge.TransformCommandR\bcommands\"\x9d\x01\n" +
	"\rBuildResponse\x12:\n" +
	"\x05files\x18\x01 \x03(\v2$.google.protobuf.FileDescriptorProtoR\x05files\x12>\n" +
	"\abundled\x18\x02 \x01(\v2$.google.protobuf.FileDescriptorProtoR\abundled\x12\x10\n" +
	"\x03log\x18\x03 \x03(\tR\x03log2\xef\x01\n" +
	"\x06Merger\x12H\n" +
	"\bDownload\x12\x12.merge.StringValue\x1a$.google.protobuf.FileDescriptorProto(\x010\x01\x121\n" +
	"\bDescribe\x12\x11.merge.Descriptor\x1a\x12.merge.StringValue\x124\n" +
	"\tTransform\x12\x12.merge.WalkRequest\x1a\x13.merge.WalkResponse\x122\n" +
	"\x05Build\x12\x13.merge.BuildRequest\x1a\x14.merge.BuildResponseB!Z\x1fgithub.com/accretional/merge/pbb\x06proto3"

var (
	file_proto_merge_proto_rawDescOnce sync.Once
	file_proto_merge_proto_rawDescData []byte
)

func file_proto_merge_proto_rawDescGZIP() []byte {
	file_proto_merge_proto_rawDescOnce.Do(func() {
		file_proto_merge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_merge_proto_rawDesc), len(file_proto_merge_proto_rawDesc)))
	})
	return file_proto_merge_proto_rawDescData
}

var file_proto_merge_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_merge_proto_goTypes = []any{
	(*StringValue)(nil),                         // 0: merge.StringValue
	(*Descriptor)(nil),                          // 1: merge.Descriptor
	(*FieldModification)(nil),                   // 2: merge.FieldModification
	(*ServiceModification)(nil),                 // 3: merge.ServiceModification
	(*TransformCommand)(nil),                    // 4: merge.TransformCommand
	(*MergeMessages)(nil),                       // 5: merge.MergeMessages
	(*RenameSymbol)(nil),                        // 6: merge.RenameSymbol
	(*RemoveField)(nil),                         // 7: merge.RemoveField
	(*WalkRequest)(nil),                         // 8: merge.WalkRequest
	(*WalkResponse)(nil),                        // 9: merge.WalkResponse
	(*BuildRequest)(nil),                        // 10: merge.BuildRequest
	(*BuildResponse)(nil),                       // 11: merge.BuildResponse
	(*descriptorpb.DescriptorProto)(nil),        // 12: google.protobuf.DescriptorProto
	(*descriptorpb.MethodDescriptorProto)(nil),  // 13: google.protobuf.MethodDescriptorProto
	(*descriptorpb.ServiceDescriptorProto)(nil), // 14: google.protobuf.ServiceDescriptorProto
	(*descriptorpb.FileDescriptorProto)(nil),    // 15: google.protobuf.FileDescriptorProto
	(*descriptorpb.FieldDescriptorProto)(nil),   // 16: google.protobuf.FieldDescriptorProto
	(*descriptorpb.EnumDescriptorProto)(nil),    // 17: google.protobuf.EnumDescriptorProto
}
var file_proto_merge_proto_depIdxs = []int32{
	12, // 0: merge.Descriptor.message:type_name -> google.protobuf.DescriptorProto
	13, // 1: merge.Descriptor.method:type_name -> google.protobuf.MethodDescriptorProto
	14, // 2: merge.Descriptor.service:type_name -> google.protobuf.ServiceDescriptorProto
	15, // 3: merge.Descriptor.file:type_name -> google.protobuf.FileDescriptorProto
	16, // 4: merge.Descriptor.field:type_name -> google.protobuf.FieldDescriptorProto
	17, // 5: merge.Descriptor.enum:type_name -> google.protobuf.EnumDescriptorProto
	2,  // 6: merge.TransformCommand.add_field:type_name -> merge.FieldModification
	3,  // 7: merge.TransformCommand.add_method:type_name -> merge.ServiceModification
	5,  // 8: merge.TransformCommand.merge_messages:type_name -> merge.MergeMessages
	6,  // 9: merge.TransformCommand.rename:type_name -> merge.RenameSymbol
	7,  // 10: merge.TransformCommand.remove_field:type_name -> merge.RemoveField
	15, // 11: merge.WalkRequest.file:type_name -> google.protobuf.FileDescriptorProto
	4,  // 12: merge.WalkRequest.commands:type_name -> merge.TransformCommand
	15, // 13: merge.WalkResponse.file:type_name -> google.protobuf.FileDescriptorProto
	4,  // 14: merge.BuildRequest.commands:type_name -> merge.TransformCommand
	15, // 15: merge.BuildResponse.files:type_name -> google.protobuf.FileDescriptorProto
	15, // 16: merge.BuildResponse.bundled:type_name -> google.protobuf.FileDescriptorProto
	0,  // 17: merge.Merger.Download:input_type -> merge.StringValue
	1,  // 18: merge.Merger.Describe:input_type -> merge.Descriptor
	8,  // 19: merge.Merger.Transform:input_type -> merge.WalkRequest
	10, // 20: merge.Merger.Build:input_type -> merge.BuildRequest
	15, // 21: merge.Merger.Download:output_type -> google.protobuf.FileDescriptorProto
	0,  // 22: merge.Merger.Describe:output_type -> merge.StringValue
	9,  // 23: merge.Merger.Transform:output_type -> merge.WalkResponse
	11, // 24: merge.Merger.Build:output_type -> merge.BuildResponse
	21, // [21:25] is the sub-list for method output_type
	17, // [17:21] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_proto_merge_proto_init() }
func file_proto_merge_proto_init() {
	if File_proto_merge_proto != nil {
		return
	}
	file_proto_merge_proto_msgTypes[1].OneofWrappers = []any{
		(*Descriptor_Message)(nil),
		(*Descriptor_Method)(nil),
		(*Descriptor_Service)(nil),
		(*Descriptor_File)(nil),
		(*Descriptor_Field)(nil),
		(*Descriptor_Enum)(nil),
	}
	file_proto_merge_proto_msgTypes[4].OneofWrappers = []any{
		(*TransformCommand_AddField)(nil),
		(*TransformCommand_AddMethod)(nil),
		(*TransformCommand_MergeMessages)(nil),
		(*TransformCommand_Rename)(nil),
		(*TransformCommand_RemoveField)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_merge_proto_rawDesc), len(file_proto_merge_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_merge_proto_goTypes,
		DependencyIndexes: file_proto_merge_proto_depIdxs,
		MessageInfos:      file_proto_merge_proto_msgTypes,
	}.Build()
	File_proto_merge_proto = out.File
	file_proto_merge_proto_goTypes = nil
	file_proto_merge_proto_depIdxs = nil
}
